
# Generated by NeuroMLlite v0.2.0

import psyneulink as pnl


conv_json_filename = 'FN.bids-mdf.json'
with open(conv_json_filename, 'r') as infile:
    json = infile.read()
    
load_model = 'load_FN_bids_mdf'
py_filename = load_model+'.py'
with open(py_filename, 'w') as outfi:
    outfi.write(pnl.generate_script_from_json(json))
    
exec('from %s import FN'%load_model)

FN.show_graph()
        
print('Ready to run network: FN')
        